
// This file is automatically generated by the Firebase setup.
// Do not edit this file manually, as any changes will be overwritten.
// Your Firebase project configuration.
export const firebaseConfig = {
  apiKey: "AIzaSyA2pq2jVrG17-WAngqgvKRMDQmr0BbyFbI",
  authDomain: "studio-3634472329-281f7.firebaseapp.com",
  projectId: "studio-3634472329-281f7",
  storageBucket: "studio-3634472329-281f7.appspot.com",
  messagingSenderId: "904988894298",
  appId: "1:904988894298:web:f655d33295c16190516463"
};
