
// This file is automatically generated by the Firebase setup.
// Do not edit this file manually, as any changes will be overwritten.
// Your Firebase project configuration.
export const firebaseConfig = {
  apiKey: "",
  authDomain: "",
  projectId: "",
  storageBucket: "",
  messagingSenderId: "",
  appId: ""
};
