
'use client';

import {Card, CardContent, CardHeader, CardTitle, CardDescription} from '@/components/ui/card';
import {useEventLogger} from '@/hooks/use-event-logger';
import {Button} from '@/components/ui/button';

export default function HistoryPage() {
  const {loggedEvents, clearEvents} = useEventLogger();

  return (
    <div className="space-y-8">
      <div className="flex justify-between items-center">
        <div>
          <h1 className="text-3xl font-bold tracking-tight">Event History</h1>
          <p className="text-muted-foreground mt-2">
            A persistent log of all events generated by the analysis agents.
          </p>
        </div>
        <Button onClick={clearEvents} variant="destructive" disabled={loggedEvents.length === 0}>
          Clear History
        </Button>
      </div>

      <Card>
        <CardHeader>
          <CardTitle>Logged Events</CardTitle>
          <CardDescription>
            Events are stored in your browser's local storage and will persist across sessions.
          </CardDescription>
        </CardHeader>
        <CardContent>
          {loggedEvents.length > 0 ? (
            <div className="space-y-4">
              {loggedEvents.map(event => (
                <div key={event.id} className="border p-4 rounded-md text-sm">
                  <p className="font-semibold">{event.description}</p>
                  <p className="text-xs text-muted-foreground mt-1">
                    <span className="font-medium">{event.agent}</span> -{' '}
                    {new Date(event.timestamp).toLocaleString()}
                  </p>
                </div>
              ))}
            </div>
          ) : (
            <p className="text-muted-foreground text-center py-8">
              No events have been logged yet. Run an analysis to see events here.
            </p>
          )}
        </CardContent>
      </Card>
    </div>
  );
}

    